CREATE TABLE `user` (
  `user_id` varchar(255) NOT NULL,
  `name` varchar(50) NOT NULL,
  `cpf` varchar(11) UNIQUE NOT NULL,
  `email` varchar(50) UNIQUE NOT NULL,
  `phone_number` varchar(24) UNIQUE NOT NULL,
  `password` varchar(25) NOT NULL,
  `creation_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `user_type` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `street` varchar(40) DEFAULT NULL,
  `number` varchar(15) DEFAULT NULL,
  `complement` varchar(150) DEFAULT NULL,
  `neighborhood` varchar(50) DEFAULT NULL,
  `zip_code` varchar(12) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  CHECK (LENGTH(name) >= 15 AND LENGTH(name) <= 50),
  CHECK (LENGTH(password) >= 8 AND LENGTH(password) <= 24),
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci