CREATE TABLE `user` (
  `user_id` varchar(36) NOT NULL,
  `username` varchar(35) UNIQUE NOT NULL,
  `full_name` varchar(35) NOT NULL,
  `cpf` varchar(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `phone_number` varchar(24) NOT NULL,
  `password` varchar(255) NOT NULL,
  `creation_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `user_type` varchar(20) DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `street` varchar(40) DEFAULT NULL,
  `number` varchar(15) DEFAULT NULL,
  `complement` varchar(150) DEFAULT NULL,
  `neighborhood` varchar(50) DEFAULT NULL,
  `zip_code` varchar(12) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `cpf` (`cpf`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `phone_number` (`phone_number`),
  CONSTRAINT `user_chk_1` CHECK (((length(`username`) >= 8) and (length(`username`) <= 35))),
  CONSTRAINT `user_chk_2` CHECK (((length(`password`) >= 8) and (length(`password`) <= 255)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
