CREATE TABLE `TB_USERS` (
  `user_id` varchar(255) NOT NULL,
  `name` varchar(80) NOT NULL,
  `cpf` varchar(11) NOT NULL,
  `email` varchar(35) NOT NULL,
  `password` varchar(30) NOT NULL,
  `phone_number` varchar(15) NOT NULL,
  `user_type` varchar(15) NOT NULL,
  `creation_date` datetime NOT NULL,
  `update_date` datetime NOT NULL,
  `zip_code` varchar(13) DEFAULT NULL,
  `street` varchar(100) DEFAULT NULL,
  `number` varchar(20) DEFAULT NULL,
  `complement` varchar(60) DEFAULT NULL,
  `neighborhood` varchar(60) DEFAULT NULL,
  `city` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `cpf` (`cpf`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci